package main

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"os/signal"
	"strings"
	"sync"
	"syscall"
	"time"
)

// StreamToken is the wire format the frontend understands.
type StreamToken struct {
	Type string `json:"type"` // "text" | "thinking" | "done" | "error"
	Text string `json:"text,omitempty"`
	Code int   `json:"code,omitempty"`
}

func writeToken(w io.Writer, t StreamToken) {
	b, _ := json.Marshal(t)
	fmt.Fprintln(w, string(b))
	if f, ok := w.(interface{ Flush() }); ok {
		f.Flush()
	}
}

// Agent represents a named sub-agent inside the harness.
type Agent struct {
	Name    string
	Model   string
	Fn      func(ctx context.Context, prompt string) (string, error)
}

// Antigravity runs a multi-agent harness with plugin support.
type Antigravity struct {
	agents map[string]*Agent
	mu     sync.RWMutex
}

func NewAntigravity() *Antigravity {
	ag := &Antigravity{agents: map[string]*Agent{}}
	// Built-in agents
	ag.RegisterAgent(&Agent{Name: "core", Model: "local", Fn: ag.coreReasoner})
	ag.RegisterAgent(&Agent{Name: "planner", Model: "local", Fn: ag.planner})
	return ag
}

func (ag *Antigravity) RegisterAgent(a *Agent) {
	ag.mu.Lock()
	defer ag.mu.Unlock()
	ag.agents[a.Name] = a
}

func (ag *Antigravity) AgentNames() []string {
	ag.mu.RLock()
	defer ag.mu.RUnlock()
	names := make([]string, 0, len(ag.agents))
	for n := range ag.agents {
		names = append(names, n)
	}
	return names
}

// coreReasoner: the default reasoning engine.
// In production this would call an LLM; here it synthesizes structured output.
func (ag *Antigravity) coreReasoner(ctx context.Context, prompt string) (string, error) {
	// Dispatch to sub-agents based on prompt intent.
	lower := strings.ToLower(prompt)

	switch {
	case strings.Contains(lower, "plan") || strings.Contains(lower, "roadmap"):
		return ag.planner(ctx, prompt)
	case strings.Contains(lower, "status") || strings.Contains(lower, "health"):
		return ag.runStatus(ctx)
	default:
		return ag.runCore(ctx, prompt)
	}
}

func (ag *Antigravity) planner(ctx context.Context, prompt string) (string, error) {
	var b strings.Builder
	b.WriteString("# Antigravity Plan\n\n")
	b.WriteString(fmt.Sprintf("**Objective:** %s\n\n", prompt))
	b.WriteString("## Execution Steps\n\n")
	b.WriteString("1. **Analyze** — Parse the objective into atomic sub-tasks.\n")
	b.WriteString("2. **Route** — Assign each sub-task to the optimal agent.\n")
	b.WriteString("3. **Execute** — Run sub-tasks in parallel where possible.\n")
	b.WriteString("4. **Validate** — Verify outputs meet success criteria.\n")
	b.WriteString("5. **Report** — Aggregate results and present to operator.\n\n")
	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("_Generated by Antigravity Planner Agent • %s_\n", time.Now().Format(time.RFC3339)))
	return b.String(), nil
}

func (ag *Antigravity) runStatus(ctx context.Context) (string, error) {
	hostname, _ := os.Hostname()
	var b strings.Builder
	b.WriteString("Antigravity Engine Status\n")
	b.WriteString("========================\n\n")
	b.WriteString(fmt.Sprintf("  Host:       %s\n", hostname))
	b.WriteString(fmt.Sprintf("  Go Runtime: %s\n", "compiled-native"))
	b.WriteString(fmt.Sprintf("  Agents:     %s\n", strings.Join(ag.AgentNames(), ", ")))
	b.WriteString(fmt.Sprintf("  Uptime:     %s\n", time.Since(time.Now().Add(-time.Millisecond)).String()))
	b.WriteString(fmt.Sprintf("  PID:        %d\n", os.Getpid()))
	b.WriteString("\nAll systems nominal.\n")
	return b.String(), nil
}

func (ag *Antigravity) runCore(ctx context.Context, prompt string) (string, error) {
	var b strings.Builder
	b.WriteString("Antigravity Core Response\n")
	b.WriteString("========================\n\n")
	b.WriteString(fmt.Sprintf("Processed: \"%s\"\n\n", prompt))
	b.WriteString("The native Go engine received your prompt via stdin and is ")
	b.WriteString("streaming structured tokens through the Node.js subprocess bridge.\n\n")
	b.WriteString("Architecture:\n")
	b.WriteString("  ├── CLI entry point (main.go)\n")
	b.WriteString("  ├── Agent registry (plugin system)\n")
	b.WriteString("  ├── Stream token encoder (JSON lines)\n")
	b.WriteString("  └── Node.js spawn bridge (route.ts)\n\n")
	b.WriteString(fmt.Sprintf("Timestamp: %s\n", time.Now().Format(time.RFC3339)))
	return b.String(), nil
}

// RunInteractive reads from stdin and streams tokens to stdout.
func (ag *Antigravity) RunInteractive(ctx context.Context, r io.Reader, w io.Writer) {
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		select {
		case <-ctx.Done():
			writeToken(w, StreamToken{Type: "done", Code: 0})
			return
		default:
		}

		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}

		// Parse the input as JSON with a "prompt" field, or treat raw text as prompt.
		var req struct {
			Prompt string `json:"prompt"`
		}
		if err := json.Unmarshal([]byte(line), &req); err != nil {
			req.Prompt = line
		}

		// Stream thinking token
		writeToken(w, StreamToken{
			Type: "thinking",
			Text: fmt.Sprintf("Dispatching to core agent for: %q", req.Prompt[:min(len(req.Prompt), 60)]),
		})

		// Run the core agent
		result, err := ag.coreReasoner(ctx, req.Prompt)
		if err != nil {
			writeToken(w, StreamToken{Type: "error", Text: err.Error()})
			writeToken(w, StreamToken{Type: "done", Code: 1})
			return
		}

		// Stream the result as text token
		writeToken(w, StreamToken{Type: "text", Text: result})
		writeToken(w, StreamToken{Type: "done", Code: 0})
	}

	writeToken(w, StreamToken{Type: "done", Code: 0})
}

// RunOnce processes a single prompt (from --prompt flag) and streams tokens.
func (ag *Antigravity) RunOnce(ctx context.Context, prompt string, w io.Writer) {
	// Stream thinking token
	writeToken(w, StreamToken{
		Type: "thinking",
		Text: fmt.Sprintf("Dispatching to core agent for: %q", prompt[:min(len(prompt), 60)]),
	})

	result, err := ag.coreReasoner(ctx, prompt)
	if err != nil {
		writeToken(w, StreamToken{Type: "error", Text: err.Error()})
		writeToken(w, StreamToken{Type: "done", Code: 1})
		return
	}

	writeToken(w, StreamToken{Type: "text", Text: result})
	writeToken(w, StreamToken{Type: "done", Code: 0})
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func main() {
	// Create Antigravity engine
	engine := NewAntigravity()

	// Context with signal handling
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sigCh
		cancel()
	}()

	// Parse flags
	args := os.Args[1:]

	// Check for --prompt flag
	var prompt string
	for i, a := range args {
		if a == "--prompt" && i+1 < len(args) {
			prompt = args[i+1]
			break
		}
	}

	if prompt != "" {
		// Single-shot mode: --prompt "user input"
		engine.RunOnce(ctx, prompt, os.Stdout)
	} else {
		// Interactive stdin mode
		engine.RunInteractive(ctx, os.Stdin, os.Stdout)
	}

	// Suppress unused import warning
	_ = exec.Command
}
